/** GM(General MID) Program Definitions
 */


export type Program = {
    name: string,    
    number: number
};

export const GmPrograms: Program[] = [
    {name: '(Grand) Piano 1'    , number: 0}  ,
    {name: '(Bright) Piano 2'   , number: 1}  ,
    {name: '(El. Grd) Piano 3'  , number: 2}  ,
    {name: 'Honky-tonk Piano'   , number: 3}  ,
    {name: 'El.Piano 1'         , number: 4}  ,
    {name: 'El.Piano 2'         , number: 5}  ,
    {name: 'Harpsichord'        , number: 6}  ,
    {name: 'Clavi'              , number: 7}  ,
    {name: 'Celesta'            , number: 8}  ,
    {name: 'Glockenspiel'       , number: 9}  ,
    {name: 'Music Box'          , number: 10} ,
    {name: 'Vibraphone'         , number: 11} ,
    {name: 'Marimba'            , number: 12} ,
    {name: 'Xylophone'          , number: 13} ,
    {name: 'Tubular Bells'      , number: 14} ,
    {name: 'Santur'             , number: 15} ,
    {name: 'Drawbar Organ'      , number: 16} ,
    {name: 'Percussive Organ'   , number: 17} ,
    {name: 'Rock Organ'         , number: 18} ,
    {name: 'Church Organ'       , number: 19} ,
    {name: 'Reed Organ'         , number: 20} ,
    {name: 'Accordion (french)' , number: 21} ,
    {name: 'Harmonica'          , number: 22} ,
    {name: 'Tango Accordion'    , number: 23} ,
    {name: 'Ac.Guitar (nylon)'  , number: 24} ,
    {name: 'Ac.Guitar (steel)'  , number: 25} ,
    {name: 'El.Guitar (jazz)'   , number: 26} ,
    {name: 'El.Guitar (clean)'  , number: 27} ,
    {name: 'El.Guitar (muted)'  , number: 28} ,
    {name: 'Overdriven Guitar'  , number: 29} ,
    {name: 'Distortion Guitar'  , number: 30} ,
    {name: 'Guitar harmonics'   , number: 31} ,
    {name: 'Acoustic Bass'      , number: 32} ,
    {name: 'Finger Bass'        , number: 33} ,
    {name: 'Picked Bass'        , number: 34} ,
    {name: 'Fretless Bass'      , number: 35} ,
    {name: 'Slap Bass 1'        , number: 36} ,
    {name: 'Slap Bass 2'        , number: 37} ,
    {name: 'Synth Bass 1'       , number: 38} ,
    {name: 'Synth Bass 2'       , number: 39} ,
    {name: 'Violin'             , number: 40} ,
    {name: 'Viola'              , number: 41} ,
    {name: 'Cello'              , number: 42} ,
    {name: 'Contrabass'         , number: 43} ,
    {name: 'Tremolo Strings'    , number: 44} ,
    {name: 'Pizzicato Strings'  , number: 45} ,
    {name: 'Orchestral Harp'    , number: 46} ,
    {name: 'Timpani'            , number: 47} ,
    {name: 'String Ensemble 1'  , number: 48} ,
    {name: 'String Ensemble 2'  , number: 49} ,
    {name: 'Synth Strings 1'    , number: 50} ,
    {name: 'Synth Strings 2'    , number: 51} ,
    {name: 'Choir Aahs'         , number: 52} ,
    {name: 'Voice Oohs'         , number: 53} ,
    {name: 'Synth Voice'        , number: 54} ,
    {name: 'Orchestra Hit'      , number: 55} ,
    {name: 'Trumpet'            , number: 56} ,
    {name: 'Trombone'           , number: 57} ,
    {name: 'Tuba'               , number: 58} ,
    {name: 'Muted Trumpet'      , number: 59} ,
    {name: 'French Horn'        , number: 60} ,
    {name: 'Brass Section'      , number: 61} ,
    {name: 'Synth Brass 1'      , number: 62} ,
    {name: 'Synth Brass 2'      , number: 63} ,
    {name: 'Soprano Sax'        , number: 64} ,
    {name: 'Alto Sax'           , number: 65} ,
    {name: 'Tenor Sax'          , number: 66} ,
    {name: 'Baritone Sax'       , number: 67} ,
    {name: 'Oboe'               , number: 68} ,
    {name: 'English Horn'       , number: 69} ,
    {name: 'Bassoon'            , number: 70} ,
    {name: 'Clarinet'           , number: 71} ,
    {name: 'Piccolo'            , number: 72} ,
    {name: 'Flute'              , number: 73} ,
    {name: 'Recorder'           , number: 74} ,
    {name: 'Pan Flute'          , number: 75} ,
    {name: 'Blown Bottle'       , number: 76} ,
    {name: 'Shakuhachi'         , number: 77} ,
    {name: 'Whistle '           , number: 78} ,
    {name: 'Ocarina '           , number: 79} ,
    {name: 'Lead 1 (square) '   , number: 80} ,
    {name: 'Lead 2 (sawtooth) ' , number: 81} ,
    {name: 'Lead 3 (calliope) ' , number: 82} ,
    {name: 'Lead 4 (chiff) '    , number: 83} ,
    {name: 'Lead 5 (charang) '  , number: 84} ,
    {name: 'Lead 6 (voice) '    , number: 85} ,
    {name: 'Lead 7 (fifths) '   , number: 86} ,
    {name: 'Lead 8 (bass+lead) ', number: 87} ,
    {name: 'Pad 1 (fantasia) '  , number: 88} ,
    {name: 'Pad 2 (warm) '      , number: 89} ,
    {name: 'Pad 3 (polysynth) ' , number: 90} ,
    {name: 'Pad 4 (choir) '     , number: 91} ,
    {name: 'Pad 5 (bowed) '     , number: 92} ,
    {name: 'Pad 6 (metallic) '  , number: 93} ,
    {name: 'Pad 7 (halo) '      , number: 94} ,
    {name: 'Pad 8 (sweep)'      , number: 95} ,
    {name: 'FX 1 (rain)'        , number: 96} ,
    {name: 'FX 2 (soundtrack)'  , number: 97} ,
    {name: 'FX 3 (crystal)'     , number: 98} ,
    {name: 'FX 4 (atmosphere)'  , number: 99} ,
    {name: 'FX 5 (brightness)'  , number: 100},
    {name: 'FX 6 (goblins)'     , number: 101},
    {name: 'FX 7 (echoes)'      , number: 102},
    {name: 'FX 8 (sci-fi)'      , number: 103},
    {name: 'Sitar'              , number: 104},
    {name: 'Banjo'              , number: 105},
    {name: 'Shamisen'           , number: 106},
    {name: 'Koto'               , number: 107},
    {name: 'Kalimba'            , number: 108},
    {name: 'Bag pipe'           , number: 109},
    {name: 'Fiddle'             , number: 110},
    {name: 'Shanai'             , number: 111},
    {name: 'Tinkle Bell'        , number: 112},
    {name: 'Agogo'              , number: 113},
    {name: 'Steel Drums'        , number: 114},
    {name: 'Woodblock'          , number: 115},
    {name: 'Taiko Drum'         , number: 116},
    {name: 'Melodic Tom'        , number: 117},
    {name: 'Synth Drum'         , number: 118},
    {name: 'Reverse Cymbal'     , number: 119},
    {name: 'Gt.Fret Noise'      , number: 120},
    {name: 'Breath Noise'       , number: 121},
    {name: 'Seashore'           , number: 122},
    {name: 'Bird Tweet'         , number: 123},
    {name: 'Teleph.Ring'        , number: 124},
    {name: 'Helicopter'         , number: 125},
    {name: 'Applause'           , number: 126},
    {name: 'Gunshot'            , number: 127},
]